server {
    server_name blog.huuthangle.site;

    listen [::]:443 ssl;
    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/blog.huuthangle.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/blog.huuthangle.site/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    return 301 https://huuthangle.site$request_uri;
}

server {
    listen 80;
    listen [::]:80;
    server_name blog.huuthangle.site;
    return 301 https://huuthangle.site$request_uri;
}
