server {
    listen 80;
    listen [::]:80;
    server_name huuthang.site;
    return 301 https://blog.huuthang.site$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name huuthang.site;

    ssl_certificate /etc/letsencrypt/live/huuthang.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/huuthang.site/privkey.pem;

    return 301 https://portfolio.huuthang.site$request_uri;
}
