server {
    listen 80;
    listen [::]:80;
    server_name ws.huuthang.site;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name ws.huuthang.site;

    ssl_certificate /etc/letsencrypt/live/ws.huuthang.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ws.huuthang.site/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass http://localhost:5001;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;

        # Optional: long-lived connections
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }
}
