services:
  backend:
    image: ghcr.io/lhuthng/blog-backend:latest
    build: ./backend
    volumes:
      - ./backend/data:/app/data
      - ./backend/media:/app/media
    container_name: rust-backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - appnet
    ports:
      - "127.0.0.1:3001:3000"
    env_file:
      - ./backend/.env

  frontend:
    image: ghcr.io/lhuthng/blog-frontend:latest
    build: ./frontend
    container_name: svelte-frontend
    depends_on:
      - backend
    networks:
      - appnet
    ports:
      - "127.0.0.1:5000:8080"
    env_file:
      - ./frontend/.env
    environment:
      - PORT=8080
      - API_URL=http://backend:3000
      - BODY_SIZE_LIMIT=100M

networks:
  appnet:
    driver: bridge
