name: Deploy My Page

on:
  push:
    branches: [master]
    paths:
      - ".github/workflows/**"
      - "blog/**"
      - "socket-server/**"

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      blog: ${{ steps.filter.outputs.blog }}
      socket: ${{ steps.filter.outputs.socket }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            blog:
              - 'blog/**'
            socket:
              - 'socket-server/**'

  deploy-blog-backend:
    needs: filter
    if: needs.filter.outputs.blog == 'true' || contains(github.event.head_commit.message, '[deploy blog]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy blog backend
        run: flyctl deploy --remote-only
        working-directory: blog/backend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-blog-frontend:
    needs: [filter, deploy-blog-backend]
    if: needs.filter.outputs.blog == 'true' || contains(github.event.head_commit.message, '[deploy blog]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy blog frontend
        run: flyctl deploy --remote-only
        working-directory: blog/frontend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-socket-server:
    needs: filter
    if: needs.filter.outputs.socket == 'true' || contains(github.event.head_commit.message, '[deploy ws]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy socket server
        run: flyctl deploy --remote-only
        working-directory: socket-server
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
